### ISSUE TITLE
RESERVE for DUMP

### ISSUE THREAD

**Issue by thelostt** [thelink2012/gta3sc#117]
```
DUMP
RESERVE 16 // makes room for 16 bytes
ENDDUMP
```

Feature's name is likely to be changed. Could be `FILL` etc. Which one to use?

**Requirement**: `RESERVE` is only a keyword token when used in DUMP contexts, otherwise it's a valid identifier/other keyword  elsewhere.

*Note*: Enabling flag is `-fdump-reserve`.

Implementation details:

+ Fill the space with zeroes (e.g. `RESERVE 4` is equivalent to `00 00 00 00`).
+ Have an optional parameter for some value which `RESERVE` will use to fill the space with (e.g. `RESERVE 4 11` is equivalent to `11 11 11 11`).

**Comment by JuniorDjjr** [comment]
I prefer
```
DUMP
FILL 16 (FF)
ENDDUMP
```
(remembering that "( )" are optional characters)

> Note: Enabling flag is -fdump-reserve.

The idea is that this feature is disabled by default? I'd rather not.

**Comment by thelostt** [comment]
> The idea is that this feature is disabled by default? I'd rather not.

Yes, it's better because it's an extension. Just like switch (`-fswitch`), arrays (`-farrays`) `break` and `continue` in other statements (`-fbreak-continue`) etc, and the list goes on. It *should* be an opt-in feature, as it's not part of the original language design.

**Comment by JuniorDjjr** [comment]
switch etc are enabled by default.

**Comment by thelink2012** [comment]
Given the additional grammar complexity, as well as that there has never been a desire for this feature, I disagree.

The grammar cost may seem small, but **DUMP** already enters an special-context, which is bad. With this, we'd have so called keywords (which are at the root of R*-design non-compiled-commands) in those special contexts? Hmm, not cool.

I, and others, also have a great desire of ditching the use of **DUMP**s. It's used nowdays for static-content and variable-expansion (although **ALLOCATE_MEMORY** can be used as well). The correct solution for this is to actually give the scripting environment (*CLEO*) the power of dynamically allocating local variables for a script, depending on its need.

Furthermore, if you still want to add lots of zeroes to the script, I believe it should be explicit that you are adding lots of these to the bytecode, by making you type each and all of them. Do remember that *CLEO* never frees the memory allocated for an piece of bytecode because of our legacy of embedding assembly code and detouring native code to those pieces of data.

Given operating system mechanisms of preventing execution of data (DEP), and the problem this introduced of not freeing bytecode, this can now be considered a bad practice. And so *DUMP*s will, once dynamic locals are available, be obsolete.

**Comment by thelostt** [comment]
Fair enough.
