### ISSUE TITLE
Support for passing strings in Cleo Call

### ISSUE THREAD

**Issue by inanahammad** [thelink2012/gta3sc#118]
while making a script i found that gta3sc doesnt support strings passing by cleo call.
More here http://brmodstudio.forumeiros.com/t6018p25-13-gosub-e-cleo_call#273946
Can this be added in future releases?

**Comment by thelink2012** [comment]
This is a complicated issue because CLEO calls only support receiving strings as integer pointers. So it's about language design, what would be good semantics to solve this problem elegantly.

Will close this because it's already open as #86, but feel free to ask any questions or provide suggestions :)
